/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author cris
 */
public class GestionOrdenes extends javax.swing.JFrame {

    
    String user;
    
    /* Variable para enviar datos entre las ventanas */
    public static String orden_update = "";
    /* Accesos a metodos para modificar datos en el interior de la tabla */
    DefaultTableModel model = new DefaultTableModel();
    
    /**
     * Creates new form OrdenesRegistradas
     */
    public GestionOrdenes() {
        initComponents();
        user = Login.user;
        
        setSize(700, 500);
        setTitle("Gestión de Órdenes");
        setResizable(false);
        setLocationRelativeTo(null);
        
        /* Con esto evitamos que el programa finalice cuando se cierra la ventana */
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon fondo = new ImageIcon("src/imagenes/fondoLogin.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_Fondo.getWidth(),jLabel_Fondo.getHeight(),
                Image.SCALE_DEFAULT));
        
        jLabel_Fondo.setIcon(icono);
        this.repaint();
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
            "select ID, STATUS, CREATEDAT, SHIPPINGPRICE from PUNTOVENTAS_ORDERS");
            
            ResultSet rs = pst.executeQuery();
            /* Se utiliza el jtable de ordenes */
            jTable_ordenes = new JTable(model);
            /* Se utiliza para usar un scroll en caso de que la cantidad de datos sea mucha mas grande que la tabla */
            jScrollPane1.setViewportView(jTable_ordenes);
            
            /* Añado las columnas que voy a utilizar. La primera es el ID */
            model.addColumn(" ");
            model.addColumn("ESTADO");
            model.addColumn("Fecha de orden");
            model.addColumn("Precio");
            
            
            while(rs.next()) {
                /* Vector de tipo Object por el tipo de dato que tiene el JTable */ 
                /* Ademas agregamos 4 por las 4 columnas que hay en nuestra tabla*/
                Object[] fila = new Object[4];
                
                /* Mientras i sea menor a 4(cantidad de columnas) este se irá incrementando */
                for (int i = 0; i < 4; i++) {
                    /* Aquí obtenemos los objetos i + 1 puesto que aquí recorrera a partir de 0 y subando 1 hasta la cantidad de columnas*/
                    fila[i] = rs.getObject(i + 1);
                }
                /* Aquí agrego las filas encontradas a nuestro objeto model */
                model.addRow(fila);
            }
            cn.close();
        } catch (Exception e) {
            System.err.println("Error al llenar con datos la tabla" + e);
            JOptionPane.showMessageDialog(null, "Error al visualizar los datos de la tabla");
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Favicon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ordenes = new javax.swing.JTable();
        jLabel_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Órdenes realizadas");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jTable_ordenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_ordenes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, 180));
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionOrdenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_ordenes;
    // End of variables declaration//GEN-END:variables
}
