/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author cris
 */
public class GraficoLineal extends javax.swing.JFrame {

    String user;
    /**
     * Creates new form GraficoLineal
     */
    public GraficoLineal() {
        initComponents();
        
        user = Login.user;
        
        setSize(550, 450);
        setTitle("Gráfico de órdenes por mes");
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon fondo = new ImageIcon("src/imagenes/fondoLogin.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_Fondo.getWidth(),jLabel_Fondo.getHeight(),
                Image.SCALE_DEFAULT));
        jLabel_Fondo.setIcon(icono);
        this.repaint();
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Favicon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_Cantidad5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Cantidad4 = new javax.swing.JTextField();
        jTextField_Cantidad3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Cantidad2 = new javax.swing.JTextField();
        jTextField_Cantidad1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel_Lineal = new javax.swing.JPanel();
        jLabel_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField_Cantidad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 60, -1));

        jLabel6.setText("Diciembre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jLabel5.setText("Noviembre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));
        getContentPane().add(jTextField_Cantidad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 60, -1));
        getContentPane().add(jTextField_Cantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 70, -1));

        jLabel4.setText("Octubre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jLabel3.setText("Septiembre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));
        getContentPane().add(jTextField_Cantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 60, -1));
        getContentPane().add(jTextField_Cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, -1));

        jLabel2.setText("Agosto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jButton1.setText("Generar gráfico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));
        getContentPane().add(jPanel_Lineal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 530, 240));
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        // Clase a utilizar de nuestra libreria 
        XYSeries serie = new XYSeries("Órdenes");
        // Defino las variables tipo entero en donde almacenare las cantidades que se escriben en los campos de texto

        int cantidad1 = Integer.parseInt(jTextField_Cantidad1.getText());
        int cantidad2 = Integer.parseInt(jTextField_Cantidad2.getText());
        int cantidad3 = Integer.parseInt(jTextField_Cantidad3.getText());
        int cantidad4 = Integer.parseInt(jTextField_Cantidad4.getText());
        int cantidad5 = Integer.parseInt(jTextField_Cantidad5.getText());
        
        // Se asigna eje X y eje Y
        serie.add(1, cantidad1);
        serie.add(2, cantidad2);
        serie.add(3, cantidad3);
        serie.add(4, cantidad4);
        serie.add(5, cantidad5);

        // Data set guarda la data para los gráficos
        XYSeriesCollection datos = new XYSeriesCollection();
        // Añado el objeto de serie a nuestro dataset
        datos.addSeries(serie);
        
        
        // Creación del gráfico
        JFreeChart lineal = ChartFactory.createXYLineChart(
                "Órdenes realizadas", 
                "Meses", 
                "Cantidad de órdenes", 
                datos, 
                PlotOrientation.VERTICAL, 
                true,
                true, 
                false);
        
        ChartPanel panel = new ChartPanel(lineal);
        
        // Establecemos el borde 
        jPanel_Lineal.setLayout(new java.awt.BorderLayout());
        // Agregamos el panel a nuestro jPanel
        jPanel_Lineal.add(panel);
        // Para visualizar correctamente se valida
        jPanel_Lineal.validate();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficoLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficoLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficoLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficoLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficoLineal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JPanel jPanel_Lineal;
    private javax.swing.JTextField jTextField_Cantidad1;
    private javax.swing.JTextField jTextField_Cantidad2;
    private javax.swing.JTextField jTextField_Cantidad3;
    private javax.swing.JTextField jTextField_Cantidad4;
    private javax.swing.JTextField jTextField_Cantidad5;
    // End of variables declaration//GEN-END:variables
}
