/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author cris
 */
public class GraficoBarras extends javax.swing.JFrame {

    String user;
    
    /**
     * Creates new form GraficoEstado
     */
    public GraficoBarras() {
        initComponents();
        
        user = Login.user;
        
        setSize(550, 450);
        setTitle("Gráfico de órdenes por mes");
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon fondo = new ImageIcon("src/imagenes/fondoLogin.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_Fondo.getWidth(),jLabel_Fondo.getHeight(),
                Image.SCALE_DEFAULT));
        jLabel_Fondo.setIcon(icono);
        this.repaint();
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Favicon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel_Barras = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Cantidad1 = new javax.swing.JTextField();
        jTextField_Cantidad2 = new javax.swing.JTextField();
        jTextField_Cantidad3 = new javax.swing.JTextField();
        jTextField_Cantidad4 = new javax.swing.JTextField();
        jTextField_Cantidad5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Gráfico de Estado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 190, 30));
        getContentPane().add(jPanel_Barras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 510, 230));

        jLabel2.setText("Agosto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setText("Septiembre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel4.setText("Octubre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel5.setText("Noviembre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel6.setText("Diciembre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));
        getContentPane().add(jTextField_Cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, -1));
        getContentPane().add(jTextField_Cantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 60, -1));
        getContentPane().add(jTextField_Cantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 70, -1));
        getContentPane().add(jTextField_Cantidad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 60, -1));
        getContentPane().add(jTextField_Cantidad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 60, -1));

        jButton1.setText("Generar gráfico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // Defino las variables tipo entero en donde almacenare las cantidades que se escriben en los campos de texto
        
        int cantidad1 = Integer.parseInt(jTextField_Cantidad1.getText());
        int cantidad2 = Integer.parseInt(jTextField_Cantidad2.getText());
        int cantidad3 = Integer.parseInt(jTextField_Cantidad3.getText());
        int cantidad4 = Integer.parseInt(jTextField_Cantidad4.getText());
        int cantidad5 = Integer.parseInt(jTextField_Cantidad5.getText());
        
        
        // Defino una clase la cual sirve para comenzar a graficar
        
        DefaultCategoryDataset datos = new DefaultCategoryDataset();
         
        // Aquí establecemos los valores que llevará nuestro grafico, gracias al metodo setValue donde le agregamos
        // la cantidad, las ordenes y los meses
        datos.setValue(cantidad1, "Órdenes", "Agosto");
        datos.setValue(cantidad2, "Órdenes", "Septiembre");
        datos.setValue(cantidad3, "Órdenes", "Octubre");
        datos.setValue(cantidad4, "Órdenes", "Noviembre");
        datos.setValue(cantidad5, "Órdenes", "Diciembre");
        
        JFreeChart barras = ChartFactory.createBarChart3D(
                "Órdenes realizadas",           //Nombre del gráfico
                "Meses",                        //Nombre de las barras
                "Órdenes",                      //Nombre de la numeración
                datos,                          //Datos del gráfico
                PlotOrientation.VERTICAL,       //Orientación del gráfico
                true,                           //Leyendas de barras
                true,                           //Herramientas 
                false                           //Url del gráfico
                
        );
        
        // Acá creo un objeto de la clase ChartPanel proveniente de la librería y a este le asigno el grafico "barras"
        ChartPanel panel = new ChartPanel(barras);
        // Es para interactuar con la rueda del mouse
        panel.setMouseWheelEnabled(true);
        // Dimensiones del panel
        panel.setPreferredSize(new Dimension(510,230));
        
        // Establecemos el borde 
        jPanel_Barras.setLayout(new BorderLayout());
        // Agregamos el panel a nuestro jPanel
        jPanel_Barras.add(panel, BorderLayout.NORTH);
        
        //Muestra y vuelve a re pintar el gráfico 
        pack();
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficoBarras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficoBarras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficoBarras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficoBarras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficoBarras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JPanel jPanel_Barras;
    private javax.swing.JTextField jTextField_Cantidad1;
    private javax.swing.JTextField jTextField_Cantidad2;
    private javax.swing.JTextField jTextField_Cantidad3;
    private javax.swing.JTextField jTextField_Cantidad4;
    private javax.swing.JTextField jTextField_Cantidad5;
    // End of variables declaration//GEN-END:variables
}
