/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author cris
 */
public class Perfil extends javax.swing.JFrame {

    String user, username, nombre, apellido, correo;
    
    /**
     * Creates new form Perfil
     */
    public Perfil() {
        initComponents();
        user = Login.user;
        
        setSize(500, 450);
        setTitle("Pérfil de Supervisor");
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon fondo = new ImageIcon("src/imagenes/blanco.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_Fondo.getWidth(),jLabel_Fondo.getHeight(),
                Image.SCALE_DEFAULT));
        jLabel_Fondo.setIcon(icono);
        this.repaint();
                
        ImageIcon logo_supervisor = new ImageIcon("src/imagenes/logo_supervisor.png");
        Icon icono_supervisor = new ImageIcon(logo_supervisor.getImage().getScaledInstance(jLabel_logoSupervisor.getWidth(),jLabel_logoSupervisor.getHeight(),
                Image.SCALE_DEFAULT));
        jLabel_logoSupervisor.setIcon(icono_supervisor);
        this.repaint();
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
            "select * from PUNTOVENTAS_USER where USERNAME = '" + user + "'");
            
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                username = rs.getString("USERNAME");
                nombre = rs.getString("FIRST_NAME");
                apellido = rs.getString("LAST_NAME");
                correo = rs.getString("EMAIL");
                
                txt_NombreUsuario.setText(username);
                txt_Nombre.setText(nombre);
                txt_Apellido.setText(apellido);
                txt_Correo.setText(correo);
            }
            if (rs.next()) {
                
            }
            cn.close();
        } catch (Exception e) {
            System.err.println("Error al cargar datos de usuario" + e);
            JOptionPane.showMessageDialog(null, "Error al obtener los datos!");
        }
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Favicon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_NombreUsuario = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Apellido = new javax.swing.JLabel();
        jLabel_Correo = new javax.swing.JLabel();
        txt_NombreUsuario = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        txt_Apellido = new javax.swing.JTextField();
        txt_Correo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_logoSupervisor = new javax.swing.JLabel();
        jLabel_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NombreUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_NombreUsuario.setText("Nombre de usuario");
        getContentPane().add(jLabel_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 100, -1, -1));

        jLabel_Nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_Nombre.setText("Nombre");
        getContentPane().add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 170, -1, -1));

        jLabel_Apellido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_Apellido.setText("Apellido");
        getContentPane().add(jLabel_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 240, -1, -1));

        jLabel_Correo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_Correo.setText("Correo eléctronico");
        getContentPane().add(jLabel_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 310, -1, -1));

        txt_NombreUsuario.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txt_NombreUsuario.setEnabled(false);
        getContentPane().add(txt_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 25));

        txt_Nombre.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txt_Nombre.setEnabled(false);
        txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreKeyTyped(evt);
            }
        });
        getContentPane().add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 220, 25));

        txt_Apellido.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txt_Apellido.setEnabled(false);
        txt_Apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 220, 25));

        txt_Correo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txt_Correo.setEnabled(false);
        getContentPane().add(txt_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 220, 25));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Perfil de Supervisor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));
        getContentPane().add(jLabel_logoSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 160, 160));
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreKeyTyped

        char c = evt.getKeyChar();
        
        if((c<'a' || c>'z') && (c<'A' || c>'Z')) evt.consume();
        
        
    }//GEN-LAST:event_txt_NombreKeyTyped

    private void txt_ApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApellidoKeyTyped
        
        char c = evt.getKeyChar();
        
        if((c<'a' || c>'z') && (c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_txt_ApellidoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Apellido;
    private javax.swing.JLabel jLabel_Correo;
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_NombreUsuario;
    private javax.swing.JLabel jLabel_logoSupervisor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Apellido;
    private javax.swing.JTextField txt_Correo;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_NombreUsuario;
    // End of variables declaration//GEN-END:variables
}
